### ISSUE TITLE
Generates faulty prompt when using attention syntax (subprompt:weight)

### ISSUE THREAD

**Issue by tijszwinkels** [ZeldaFan0225/Stable_Horde_Discord#10]
For example, for the following prompt:

`a cat (wearing a wig:1.2) looks up to the camera with it's eyes wide open and a brown fur on top`

it sends the prompt:

`a cat (wearing a wig:1.2:1.1) looks up to the camera with it's eyes wide open and a brown fur on top`

Presumably because it tries to raise the weight when using () around a prompt automatically.

**Comment by ZeldaFan0225** [comment]
fixed
