### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by elegos** [ZeldaFan0225/Stable_Horde_Discord#14]
**Describe the bug**
When the `:5K_sensational:` emote is being used as reaction, 10.000 kudos are being donated

**To Reproduce**
1. React to a Discord message with the `:5K_sensational:` emote

**Expected behavior**
You should donate 5.000 kudos, not 10.000

**Screenshots**
![image](https://user-images.githubusercontent.com/577975/213671701-041b6ee1-134b-482a-afb3-e9c90934d6ff.png)
![image](https://user-images.githubusercontent.com/577975/213671793-e8b1983e-121c-4882-b629-0be3d1183574.png)

**Additional context**
n/a

**Comment by ZeldaFan0225** [comment]
this is a matter of configuration, there is nothing wrong about the bots code
