### ISSUE TITLE
In a party, whens selecting the wrong style, the error message is bugged

### ISSUE THREAD

**Issue by db0** [ZeldaFan0225/Stable_Horde_Discord#28]
**Describe the bug**
If you manually type the wrong model, you get this message

![image](https://user-images.githubusercontent.com/296513/219946366-dedfbf79-4dd9-46fc-9b43-8b4b550592ba.png)

Should probably be reporting the right style to use

**Comment by ZeldaFan0225** [comment]
It shows that you can only use /generate, this has been fixed already

**Comment by db0** [comment]
My bad. I had sent my own requests with a different style and I thought the error was from that as well
